.gitignore, README.md, index.js, package-lock.json, package.json
=> [FEAT] #2 added support for tsconfig paths

dummy.js/package.json, index.js, package-lock.json, tests/.eslintrc.js, tests/index.ts
If the "import/extensions" rule is activated then the following import statement causes the error:
```
import "popper.js";
```
causes the following error
```
Resolve error: Cannot find module 'popper' from 'D:\Projects\eslint-import-resolver-typescript\tests'  import/extensions
```
This code is ported from the previous version of the file https://github.com/alexgorbatchev/eslint-import-resolver-typescript/commit/87a9e00f92c7313dda0e57b0b8ed8b0d74abef39#diff-168726dbe96b3ce427e7fedce31bb0bcL20
These changes fixes this error. I do not know how to test it correctly via unit test because we need to install some npm package with ".js" suffix in the name for this test.
=> [FIX] #7 node_modules with .js in the name

.travis.yml, README.md, index.js, package.json, prettier.config.js, tests/baseEslintConfig.js
adding travis to get automatic validation of PRs.
I've tested it and it's currently passing:
https://travis-ci.org/bradzacher/eslint-import-resolver-typescript/builds/446812404
@alexgorbatchev as part of this (if you're all good with it!), please:
- activate travis on the repo (https://travis-ci.org/alexgorbatchev/eslint-import-resolver-typescript/)
- add a branch protection rule to master (https://github.com/alexgorbatchev/eslint-import-resolver-typescript/settings/branch_protection_rules/new) (might have to trigger a build via "More Options" before it'll show up)
=> [TEST] Add travis

README.md
We noticed some unrelated errors when changing the global parser, so this was the fix that worked in our case and follows the structure from the `eslint-plugin-import` docs to change the parser for `import` and restrict it to `.ts` and `.tsx` files.
https://github.com/benmosher/eslint-plugin-import#importparsers
=> Change recommended configuration to use plugin-specific parser rather than changing global parser

src/index.ts
Closes https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/25
As discussed, this makes it possible to resolve files with `.jsx` extension, when using `allowJs` option.
=> Resolve files with jsx extension

package.json, src/index.ts, tests/withJsExtension/.eslintrc.js, tests/withJsExtension/bar/index.tsx, tests/withJsExtension/dtsImportee.d.ts, tests/withJsExtension/foo.js/index.ts, tests/withJsExtension/foo.jsx/index.ts, tests/withJsExtension/foo/index.ts, tests/withJsExtension/index.ts, tests/withJsExtension/test.js, tests/withJsExtension/tsImportee.ts, tests/withJsExtension/tsconfig.json, tests/withJsExtension/tsxImportee.tsx
=> feat: import with .js and .jsx file extensions

package.json
I was doing a script to remove all `.tsbuildinfo` files from my monorepo and noted that this package is distributing those files. I got something like this:
```sh
$ find . -name '*.tsbuildinfo'
./node_modules/eslint-import-resolver-typescript/lib/tsconfig.tsbuildinfo
./packages/A/dist/tsconfig.tsbuildinfo
./packages/B/dist/tsconfig.tsbuildinfo
./packages/C/dist/tsconfig.tsbuildinfo
```
I think those files shouldn't be distributed, so I've filtered them out of the package. I've also left out `.d.ts.map` files, as they are unusable without the original sources, which are not distributed on the package.
I **don't** think we should stop generating `.tsbuildinfo` and `.d.ts.map` files, as they are useful for build performance and development experience. We should just not distribute them.
=> fix: remove .tsbuildinfo and d.ts.map files from package

README.md
I thought that the config below would be valid since it was demonstrated on the README.
```
{
"typescript": {
"alwaysTryTypes": true // always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`
},
// use <root>/path/to/folder/tsconfig.json
"typescript": {
"project": "path/to/folder"
},
}
```
It turns out the `typescript` blocks are not merged and overwrite each other. This PR updates the example on the README so as to not demonstrate multiple `typescript` blocks
=> docs: clarify example in README

package.json, src/index.ts, tests/withQuerystring/.eslintrc.js, tests/withQuerystring/image.svg, tests/withQuerystring/index.ts, tests/withQuerystring/subfolder/image.svg, tests/withQuerystring/tsconfig.json
[Vite](https://vitejs.dev/) supports querystrings in imports like for instance: `import svg from "./image.svg?raw"` (imports the file contents as a string).
Such an import gets wrongly marked as unresolved by the rule `import/no-unresolve` when using this resolver.
The [webpack resolver](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack) strips querystrings so that `import/no-unresolve` correctly can resolve those imports.
This PR adds the same feature to `eslint-import-resolver-typescript`.
=> feat: remove any querystring from imports

package.json, src/index.ts, tests/withPathsAndNestedBaseUrl/.eslintrc.js, tests/withPathsAndNestedBaseUrl/other/bar.ts, tests/withPathsAndNestedBaseUrl/root/foo.ts, tests/withPathsAndNestedBaseUrl/tsconfig.json
Fixes https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/68
=> Remove redundant condition

src/index.ts
letting us pass our own options (via settings in .eslintrc.js allows us to override all of the settings specified in https://www.npmjs.com/package/resolve - not just the ones this project "knows" about. spreading these first will ensure that the settings this project knows about will still work/override as expected while letting others pass through.
=> feature: allow passing through custom options to resolve

src/index.ts, tests/withJsExtension/cjsImportee.cjs, tests/withJsExtension/ctsImportee.cts, tests/withJsExtension/d-ctsImportee.d.cts, tests/withJsExtension/d-mtsImportee.d.mts, tests/withJsExtension/foo.cjs/index.ts, tests/withJsExtension/foo.mjs/index.ts, tests/withJsExtension/jsImportee.js, tests/withJsExtension/jsxImportee.jsx, tests/withJsExtension/mjsImportee.mjs, tests/withJsExtension/mtsImportee.mts, tests/withJsExtension/test.js
close #83
prepare for [`typescript@4.5`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#new-file-extensions)
=> feat: support `.cjs` `.mjs` `.cts` `.mts` extensions

package.json, src/index.ts, yarn.lock
this ensures to not include the `node_modules` folder when expanding the `projects` option glob.
(similar to what `@typescript-eslint/parser` does, but with `globby` not `glob`, see https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/parser.ts#L296-L306)
=> feat: ignore `node_modules` folder in `projects` option glob

src/index.ts
=> fix: add conditionNames support

.changeset/tame-panthers-cheat.md, package.json, src/.eslintrc, src/index.ts, yarn.lock
=> fix: try index.d.ts automatically

.changeset/strong-beans-allow.md, .eslintignore, .github/workflows/pkg-size.yml, .github/workflows/release.yml, README.md, package.json, src/index.ts, yarn.lock
=> fix: auto try extensions

.changeset/khaki-lemons-sort.md, .changeset/shiny-kiwis-kiss.md, .changeset/stale-eggs-mate.md, .changeset/two-tables-study.md, package.json, pnpm-lock.yaml, src/index.ts, tests/withJsExtension/test.js
=> feat: add `externsionAlias` option support

.changeset/twenty-ways-yell.md, README.md, package.json, src/index.ts
=> docs: document options from `enhanced-resolve`

.changeset/neat-glasses-carry.md, package.json, src/index.ts, tests/withJsconfig/.eslintrc.cjs, tests/withJsconfig/importee.js, tests/withJsconfig/index.js, tests/withJsconfig/jsconfig.json
close #73 
tl;dr - this handles the case of `project: "path/to/jsconfig.json"` without breaking `project: "/path/to/dir"`.
If a path other than `tsconfig.json` is used, `getTsconfig` requires that the first argument is a directory and the second argument is a path.
The second argument to `getTsconfig` must not be a directory, otherwise it will try to read it as a file, resulting in an error.
The given `project` paths, or the resulting paths from globs, are passed as the first and only argument to `getTsconfig`.
In the case that the given `project` path is a file, or a glob results in a file, its parent directory will be passed as the first argument to `getTsconfig` and its base name will be the second argument.
This fixes passing full filenames other than `tsconfig.json`, ex. …
=> feat: add support for `jsconfig.json`

.changeset/nasty-points-speak.md, src/index.ts
Adds caching to the enhanced resolve as described in the docs https://github.com/webpack/enhanced-resolve#creating-a-resolver
On https://github.com/thatsmydoing/eslint-import-resolver-typescript-158, this reduces the time from 27 seconds down to 9 seconds but that's still pretty far from 2.7.1 which takes less than 3 seconds.
=> perf: add filesystem caching support

package.json, pnpm-lock.yaml
I updated dependency sycnkit to from `^0.8.1` to `^0.8.3`.
This is because synckit@^0.8.1 breaks using this pugin with Yarn PnP in VSCode.
This issue has already been reported(#164), and has been resolved in synckit(un-ts/synckit#98), but this plugin dependency has not been updated
=> chore(deps): update dependency `synckit` to ^0.8.3 for yarn PnP

.changeset/calm-ties-search.md, .changeset/ten-timers-rest.md, .eslintignore, .lintstagedrc.cjs, .remarkrc, README.md, package.json, shim.d.ts, src/index.ts, tsconfig.json
=> feat: reuse `eslint-module-utils/hash.js` for better caching

.changeset/cyan-parrots-act.md, src/index.ts
Resolves #181 
Kept `try...catch` block as [ESLint still keeps support on v12.22.0+](https://github.com/eslint/eslint#installation-and-usage) and `throwIfNoEntry` is not supported until Node 14 LTS.
=> perf: disable `throwIfNoEntry` on Node 14+

.changeset/fluffy-poets-applaud.md, package.json
importing node:fs and node:path in commonjs does not work in node 12 dependency synckit also does no longer support node 12
resolves #192
=> chore(package): remove node 12 from engines field

.changeset/mean-seals-tease.md, src/index.ts
Only resolve a module dir when we now that the mapped path is a directory. This improves linting time by about 18% in projects with lots of files.
The reason for the speedup is an accidental overhead in the callback of the filter function.
https://github.com/import-js/eslint-import-resolver-typescript/blob/46de0e8fccfc0460f336c4006f9df0263f7394c9/src/index.ts#L290 
There we check if something resolves to file, and if not we'll check if it is a module directory. But in 99% of cases we'll be resolving file extensions in this callback. If `/foo/bar/package.json` is not a file, then it's very unlikely that `/foo/bar.ts/package.json` will be, unless `/foo/bar.ts` is a directory. Before this PR we'd check for the latter regardless which lead to an `ENOTDIR` error being thrown. The mere overhead …
=> perf: avoid unnecessary `fs.statSync` calls

README.md
The link to lgtm.com is now:
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
And the badge seems not working anymore.
=> Remove lgtm badge from README

.changeset/rich-icons-hope.md, src/index.ts
Fixes https://github.com/import-js/eslint-import-resolver-typescript/issues/217
=> fix: check if cwd changed to bust mapper cache

.changeset/curly-scissors-build.md, package.json, pnpm-lock.yaml, src/index.ts
=> Fix import from CJS lib

README.md
coming from https://github.com/import-js/eslint-import-resolver-typescript/pull/243#issuecomment-1814819670, to make sure everyone is aware of how to prevent having both modules in the node_modules folder.
=> docs(readme): add a warning for eslint-plugin-i npm installation

.changeset/purple-buttons-lay.md, package.json, yarn.lock
Fixes #293 
The PR marks both `import` and `import-x` plugins as optional peer dependencies, thus disables the warning on missing `import` when you're using `import-x` instead.
=> Allow either import or import-x plugin as a peer dependency

.changeset/spotty-grapes-draw.md, package.json, src/index.ts, yarn.lock
Node.js from v6.13.0, v8.10.0, v9.3.0 includes `module.builtinModules` which we can use to natively check if some module belongs to Node.js core or not.
This drops not one, but _three_ dependencies, removing 70 KB of bloat: https://npmgraph.js.org/?q=is-core-module
=> chore(deps): remove `is-core-module` dependency

.changeset/purple-planes-grin.md, package.json, src/index.ts, yarn.lock
supersedes #266
[npm link](https://www.npmjs.com/package/is-bun-module)
=> fix: ignore bun built-in modules

.changeset/dirty-lobsters-behave.md, package.json, src/index.ts, tsconfig.json, yarn.lock
cc @wojtekmaj @SunsetTechuila
Closes #303.
Use `@nolyfill/is-core-module`.
`node:` prefix only module (`node:sea`, `node:test`) doesn't exist in `module.builtinModules`, and I want ESLint to detect typos like `node:slqite`. So we will have to maintain a data set.
The differences between `@nolyfill/is-core-module` and `is-core-module`:
- 0 dependency vs 1 dependency `hasown` (which then has a transitive dependency `function-bind`)
- Use `Set#has` instead of the `hasown` package
- Don't run the match against the Node.js version vs use the current Node.js version when not provided
- 2.7 KiB installation size vs 72 KiB installation size
=> fix(#303): use `@nolyfill/is-core-module`

.changeset/metal-insects-trade.md, .eslintignore, .vscode/settings.json, README.md, package.json, shim.d.ts, src/index.ts, tests/importXResolverV3/eslint.config.js, tests/importXResolverV3/packages/module-a/index.ts, tests/importXResolverV3/packages/module-a/subfolder/tsImportee.ts, tests/importXResolverV3/packages/module-a/subfolder/tsxImportee.tsx, tests/importXResolverV3/packages/module-a/tsImportee.ts, tests/importXResolverV3/packages/module-a/tsconfig.json, tests/importXResolverV3/packages/module-a/tsxImportee.tsx, tests/importXResolverV3/packages/module-b/index.ts, tests/importXResolverV3/packages/module-b/subfolder/tsImportee.ts, tests/importXResolverV3/packages/module-b/subfolder/tsxImportee.tsx, tests/importXResolverV3/packages/module-b/tsImportee.ts, tests/importXResolverV3/packages/module-b/tsconfig.json, tests/importXResolverV3/packages/module-b/tsxImportee.tsx, tsconfig.json, yarn.lock
Fixes #318.
Introduces support for flat config support and support for `eslint-plugin-import-x`'s v3 interface.
cc @mcshaman @melroy89 @Leonardo-Vieira-Andela
Also, README has been updated w/ the flat config usage.
-----
This version has implemented the `eslint-plugin-import-x`'s v3 resolver interface. This allows you to use import/require to reference `eslint-import-resolver-typescript` directly in your ESLint flat config:
**Previously**
```js
// eslint.config.js
module.exports = {
settings: {
'import-x/resolver': {
typescript: {
alwaysTryTypes: true,
},
// or
require.resolve('eslint-import-resolver-typescript'):
alwaysTryTypes: true,
}
}
}
}
```
**Now**
```js
// eslint.config.js
const {
createTypeScriptImportResolver,
} = require('eslint-import-resolver-typescript')
module.exports = { …
```
=> feat: implement import-x resolver interface v3

README.md
This pr removes `s` from `import/resolvers` in flat-config's settings with `eslint-plugin-import` on README.md.
* According to [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#typescript), the setting name seems to be `import/resolver`.
* With `.eslintrc`, README.md has already `import/resolver`.
With `import/resolvers` eslint shows these errors on my environment:
```
4:37  error  Unable to resolve path to module '@/constants'                       import/no-unresolved
```
With `import/resolver`, no errors are shown.
```json:tsconfig.json
{
"extends": "./node_modules/@tsconfig/node20/tsconfig.json",
"compilerOptions": {
// ...
"paths": {
"@/*": ["./src/*"]
}
}
}
```
```typescript:foo.ts
import { slackUserCacheTable } from '@/constants';
```
=> fix: README has a wrong setting name 'import/resolvers'

package.json, src/index.ts, yarn.lock
https://npmgraph.js.org/?q=fast-glob - 17 dependencies
https://npmgraph.js.org/?q=tinyglobby - 2 dependencies
=> chore: switch to tinyglobby

.changeset/brave-pets-act.md, src/index.ts
=> Fix issue 348

.changeset/loud-avocados-bake.md, .size-limit.json, src/index.ts, tests/withPaths/index.ts
=> fix: add support for importing with .js extension as tsx importee

.changeset/new-peas-fry.md, src/index.ts
=> fix: include mapper with no files and force non-dynamic projects to use absolute paths

.changeset/thin-bulldogs-fetch.md, package.json, src/index.ts, yarn.lock
Align with https://github.com/un-ts/eslint-plugin-import-x/pull/237
=> feat: migrate `enhanced-resolve` to `oxc-resolver`

README.md
close #165
close #176
close #208
close #333
close #334
=> docs: tiny improvements

.changeset/cuddly-kiwis-drum.md, .changeset/lemon-trains-hang.md, .size-limit.json, src/index.ts, src/types.ts
=> feat: add a new `bun?: boolean` option for `bun` users

.changeset/light-kangaroos-kiss.md, src/index.ts
related https://github.com/import-js/eslint-import-resolver-typescript/pull/387#discussion_r1998588563
cc @SunsetTechuila
=> fix: should prefer `module.isBuiltin` when `process.versions.bun` available

.changeset/silent-cows-drive.md, .size-limit.json, package.json, src/helpers.ts, src/index.ts, src/types.ts, yarn.lock
related https://github.com/import-js/eslint-import-resolver-typescript/pull/389#issuecomment-2729512493
Technically this is a BREAKING CHANGE, but considering we just raise out v4 recently and this only affects `bun` users, `bun --bun eslint` even works without this dependency, so I'd consider this as a minor change.
So for `bun` users, there are three options:
1. install `is-bun-module` dependency manually and use `bun: true` option
2. run `eslint` with `bun --bun eslint` w/o `bun: true` option
3. enable `run#bun` in [`bunfig.toml`](https://bun.sh/docs/runtime/bunfig#run-bun-auto-alias-node-to-bun) w/o `bun: true` option
cc @SukkaW @SunsetTechuila
=> feat: make `is-bun-module` as optional peer dependency

README.md
Hi @JounQin, hope you're well! 👋
I saw that the `bun` option from [`eslint-import-resolver-typescript@4.2.0`](https://github.com/import-js/eslint-import-resolver-typescript/releases/tag/v4.2.0) isn't documented in [the top level Configuration section in the readme](https://github.com/import-js/eslint-import-resolver-typescript#configuration)
=> Document usage with Bun
